# Generated by Django 3.0.1 on 2020-11-07 12:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField(max_length=30)),
                ('customer_mobile', models.PositiveIntegerField(default=0)),
                ('customer_email', models.TextField(default='notknown@gmail.com', max_length=70)),
                ('customer_address', models.TextField(default='no', max_length=200)),
                ('customer_state', models.TextField(default='Gujarat', max_length=30)),
                ('customer_city', models.TextField(default='Rajkot', max_length=30)),
                ('customer_pincode', models.PositiveIntegerField(default=360007, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('customer_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='gst',
            fields=[
                ('ghsncode', models.IntegerField(primary_key=True, serialize=False)),
                ('gdescription', models.TextField()),
                ('gcgst', models.FloatField()),
                ('gsgst', models.FloatField()),
                ('gigst', models.FloatField()),
                ('gtimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField(default=None)),
                ('product_id', models.IntegerField()),
                ('sp', models.FloatField()),
                ('qty', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('igst', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pcost', models.FloatField()),
                ('pmrp', models.FloatField()),
                ('psellingprice', models.FloatField()),
                ('pdiscount', models.FloatField()),
                ('ppackingdt', models.DateField()),
                ('pexpirydt', models.DateField()),
                ('pstock', models.IntegerField()),
                ('pquantity', models.IntegerField()),
                ('pqrcode', models.IntegerField()),
                ('pqrimage', models.ImageField(blank=True, upload_to='')),
                ('ptimestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phsncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MegaMart.gst')),
            ],
        ),
    ]
